
name: car_maintenance_app
description: A car maintenance app to track parts and distances.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  path_provider: ^2.0.11
  provider: ^6.0.5
  flutter_local_notifications: ^12.0.0
  